// Generated by CoffeeScript 1.3.3
(function() {
  var query_options;

  query_options = {
    default_uri: "http://google.com.au/search?q=%s"
  };

  exports.query_options = query_options;

}).call(this);
