// Generated by CoffeeScript 1.3.3
(function() {
  var handle, request_handlers, router, server;

  server = require('./server');

  router = require('./router');

  request_handlers = require('./request_handlers');

  handle = {};

  handle["/"] = request_handlers.start;

  handle["/quotes"] = request_handlers.quotes;

  handle["/fetch"] = request_handlers.fetch_stocks;

  server.start(router.route, handle);

}).call(this);
