// Generated by CoffeeScript 1.3.3
(function() {
  var env, http, jsdom, logger, mysql, request, validate_proxies;

  http = require('http');

  http.globalAgent.maxSockets = 50;

  request = require('request');

  logger = require('./logger');

  mysql = require('./db').mysql;

  jsdom = require('jsdom');

  env = require('./config/environment');

  jsdom.defaultDocumentFeatures = {
    FetchExternalResources: false,
    ProcessExternalResources: false
  };

  validate_proxies = function(response, query) {
    request = request.defaults({
      'proxy': "http://198.102.29.195:3128"
    });
    request.get("https://twitter.com", function(error, res, body) {
      if (error) {
        return logger.error("[tag:fame:error] can't open twitter");
      } else {
        return logger.info(body);
      }
    });
    return response.end();
  };

  exports.validate_proxies = validate_proxies;

}).call(this);
