// Generated by CoffeeScript 1.3.3
(function() {
  var route;

  route = function(handle, response, pathname, query) {
    if ((typeof handle[pathname]) === 'function') {
      return handle[pathname](response, query);
    } else {
      console.log("No request handler found for " + pathname);
      return "404 Not found";
    }
  };

  exports.route = route;

}).call(this);
