// Generated by CoffeeScript 1.3.3
(function() {
  var http, start, url;

  http = require('http');

  url = require('url');

  start = function(route, handle) {
    var on_request;
    on_request = function(request, response) {
      var pathname, query_string;
      pathname = url.parse(request.url).pathname;
      console.log("Request for " + pathname + " received.");
      query_string = url.parse(request.url).query;
      console.log("Request for " + query_string + " received.");
      return route(handle, response, pathname, query_string);
    };
    return http.createServer(on_request).listen(8888);
  };

  exports.start = start;

}).call(this);
