// Generated by CoffeeScript 1.3.3
(function() {
  var query_options;

  query_options = {
    default_uri: "http://www.soso.com/q?sc=web&w=%s"
  };

  exports.query_options = query_options;

}).call(this);
