// Generated by CoffeeScript 1.3.3
(function() {
  var sleep;

  sleep = function(milliSeconds) {
    var startTime, _results;
    startTime = new Date().getTime();
    _results = [];
    while (true) {
      if (new Date().getTime() > (startTime + milliSeconds)) {
        break;
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  exports.sleep = sleep;

}).call(this);
