// Generated by CoffeeScript 1.3.3
(function() {
  var query_options;

  query_options = {
    default_uri: "http://s.weibo.com/weibo/%s&timescope=custom:%s:%s&Refer=g",
    realtime_uri: "http://s.weibo.com/weibo/%s&timescope=custom:%s:%s&Refer=g&xsort=time",
    hot_uri: "http://s.weibo.com/weibo/%s&timescope=custom:%s:%s&Refer=g&xsort=hot"
  };

  exports.query_options = query_options;

}).call(this);
