// Generated by CoffeeScript 1.3.3
(function() {
  var path, settings;

  path = require("path");

  settings = {
    LOG_PATH: path.join(__dirname, "logs/stock_quotes.log"),
    DEBUG: true,
    MYSQL_HOST: "127.0.0.1",
    MYSQL_PORT: 3306,
    MYSQL_USERNAME: "root",
    MYSQL_PASSWORD: "root",
    MYSQL_DATABASE: "sns_demo_development",
    MEMCACHED_HOST: "127.0.0.1",
    MEMCACHED_PORT: 11211,
    MEMCACHED_NAMESPACE: 'sns_demo',
    STOCK_PRICE_EXPIRES: 600000,
    WEIBO_HOT_TAGS_COUNT: 100,
    PROXY_START_POINT: "http://200.146.34.44:3128"
  };

  module.exports = settings;

}).call(this);
