// Generated by CoffeeScript 1.3.3
(function() {
  var path, settings;

  path = require("path");

  settings = {
    LOG_PATH: path.join(__dirname, "logs/stock_quotes.log"),
    DEBUG: true,
    MYSQL_HOST: "127.0.0.1",
    MYSQL_PORT: 3306,
    MYSQL_USERNAME: "root",
    MYSQL_PASSWORD: "root",
    MYSQL_DATABASE: "sns_demo_development",
    MEMCACHED_HOST: "127.0.0.1",
    MEMCACHED_PORT: 11211,
    MEMCACHED_NAMESPACE: 'sns_demo',
    STOCK_PRICE_EXPIRES: 600000,
    WEIBO_HOT_TAGS_COUNT: 100,
    CHINESE_HOT_KEYS: ["同学", "逛街", "足球", "篮球", "彩票", "出租车", "今天", "相亲", "吃饭", "出门", "帅哥", "美女", "视频", "故事", "车", "房子", "儿子", "女儿", "工资", "国家", "报纸", "广播", "图片", "博客", "活动", "应用"]
  };

  module.exports = settings;

}).call(this);
